### ISSUE TITLE
Docs say that maoni-email should be included but it's not

### ISSUE THREAD

**Issue by Ninjaman494** [rm3l/maoni#253]
I was updating to `9.1.0` with the following dependencies in my `build.gradle`:
```
implementation 'org.rm3l:maoni:9.1.0@aar'
api 'org.rm3l:maoni-common:9.1.0@aar'
```

However, when I tried using Maoni builder to create a `MaoniActivity` I got a runtime error because `MaoniEmailListener` couldn't be found. I was able to fix it by adding `org.rm3l:maoni-email:9.1.0` as a dependency, but in the README it says this should already be included?

**Comment by rm3l** [comment]
Hi @Ninjaman494 !

Thanks for reporting this issue. I was able to reproduce the issue and will look into it when I get a chance.
Thanks for the suggested workaround. I will update the README accordingly, until this issue is fixed.

`maoni-email` is correctly listed as a dependency of `maoni`, as we can see in its [POM on Maven Central](https://search.maven.org/artifact/org.rm3l/maoni/9.1.0/aar). So I think another possible workaround is to import `maoni` transitively with:
```gradle
implementation('org.rm3l:maoni:9.1.0@aar') {
        transitive = true
        // Needed because of https://github.com/rm3l/maoni/issues/294
        exclude module: 'unspecified'
}
```
I just tested this successfully, but then came across this other weird issue (#294), hence the exclusion hacky rule.
